### ISSUE TITLE
Implement User interface

### ISSUE THREAD

**Issue by BenjaminFrazer** [Lilypads/PollutionSensor#6]
User interface consists of 3 main components:
1. Input handler - creates a threat which listens for user input, and calls the appropriate callbacks in the menu handler
2. Menu handler - exposes the following three callbacks and members:
Callbacks:
 - Increment() - go up one menu item
 - decrement() - go down one menu item
 - enter() - select this menu item
 Members:
 - MenuItems - array of char arrays which contain the current menu items
 - nItems - number of menu items on this level of the menu
 - menuIdx - what is the currently selected menu item
 - isActive - are we at the home screen
3. Display handler - exposes a method for rewriting information displayed to the user based on the menu state in the menu handler

**TODO**
- [ ] implement menu handler
- [ ] implement display handler (based on dummy data in the format specified by the gps and sps30 headers)
- [ ] implement display handler 
- [ ] create unit tests if relevant (i can't think of what you would test)
- [ ] create standalone demonstrator program that compiles and runs on the raspberry pi
