### ISSUE TITLE
Implement OLED display wrapper class

### ISSUE THREAD

**Issue by BenjaminFrazer** [Lilypads/PollutionSensor#7]
This project makes use of an I2C oled display with an ssd1306 (see PollutionSensor.org) to be able to use this.
This class will expose a public method updateOled() which which will start a full write of either display data from the gps and sps30 or menu data depending of if the menu handler class has the isActive flag high. In order to call the menu class, the display update class will have to be initialized with a pointer to the menu handler class. 

**TODO** 
- [ ] #14
- [ ] implement functions for displaying measurements based on sps30Mesurement, gpsMeasurment structs
- [ ] implement functions for displaying menu based on the menu state held in the menu handler class
- [ ] create a demonstration program that implements a dummy instance of the menu handler with an example menu, maybe even implement the input handler if this is ready
