### ISSUE TITLE
Create Storage Handler Class

### ISSUE THREAD

**Issue by BenjaminFrazer** [Lilypads/PollutionSensor#9]
This class exposes an addMeasurement() methods that takes as input an sps30Measurement, and a gpsMeasurement, and will then buffer the data locally until either the buffer is full, or a timer elapses. The reason for the buffering is to avoid to many individual writes to disk. The class should also expose a flush buffer method which will force the remaining buffered data to be written to disk.

**TODO**
- [x] decide on a suitable container to act as the temporary buffer between writes 
- [x] decide on a data format for the stored data, preferably human readable (csv maybe with column headers)
- [x] create a function for writing the elements of the sps30/gps measurement structs into a deliminated string 
- [x] implement the addMeasurement() method 
x [ ] create a method that pops the measurement buffer items off one at a time and concatenates them onto the string to be written
x [ ] create a write string method which takes the string to be written and writes it all into the file (note the write happens all in one go!)
- [x] create a tester program which demonstrates this with dummy sps30/gps data 
- [x] go for review / pull request
